app/test: fix debug build
When RTE_APP_TEST_DEBUG is set, there were some errors:

app/test/test_cryptodev.c: In function ‘create_gcm_operation’:
app/test/test_cryptodev.c:3619:18: error: ‘struct rte_crypto_op’ has no member named ‘digest’
     ut_params->op->digest.data,
                  ^
app/test/test_cryptodev.c:3620:18: error: ‘struct rte_crypto_op’ has no member named ‘digest’
     ut_params->op->digest.length);
                  ^
app/test/test_cryptodev.c:3662:41: error: ‘struct rte_crypto_op’ has no member named ‘iv’
  rte_hexdump(stdout, "iv:", ut_params->op->iv.data, iv_pad_len);
                                         ^
app/test/test_cryptodev.c:3664:17: error: ‘struct rte_crypto_op’ has no member named ‘additional_auth’
    ut_params->op->additional_auth.data, aad_len);

Fixes: eec136f3c54fc ("aesni_gcm: add driver for AES-GCM crypto operations")

Signed-off-by: Pablo de Lara <pablo.de.lara.guarch@intel.com>
Acked-by: Fan Zhang <roy.fan.zhang@intel.com>