ethdev: fix C11 extensions in exported TM header
Fix issues reported by check-includes.sh:

 rte_tm.h:473:2: error: anonymous unions are a C11 extension
     [-Werror,-Wc11-extensions]
 rte_tm.h:696:2: error: anonymous unions are a C11 extension
     [-Werror,-Wc11-extensions]
 rte_tm.h:904:2: error: anonymous unions are a C11 extension
     [-Werror,-Wc11-extensions]

Fixes: 5d109deffa87 ("ethdev: add traffic management API")

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
Acked-by: Cristian Dumitrescu <cristian.dumitrescu@intel.com>