xen: fix build as shared library
When building as shared library, the compiler complains for
	undefined reference to `rte_xen_mem_phy2mch'

The symbol rte_xen_mem_phy2mch was introduced in DPDK 2.2
and has been called in mempool recently via rte_mem_phy2mch.

Fixes: c042ba20674a ("mempool: rework support of Xen dom0")

Signed-off-by: Thomas Monjalon <thomas.monjalon@6wind.com>