examples/performance-thread: fix build without SSE4.1
clang reports these errors:

error: too many arguments to function call, expected 2, have 3
	examples/performance-thread/l3fwd-thread/main.c:1220:1: note:
	'l3fwd_simple_forward' declared here

examples/l3fwd/main.c:550:1: error: unused function 'send_packetsx4'

The function is used only when ENABLE_MULTI_BUFFER_OPTIMIZE is 1.

Fixes: d48415e1fee3 ("examples/performance-thread: add l3fwd-thread app")

Signed-off-by: Thomas Monjalon <thomas.monjalon@6wind.com>