cryptodev: fix C11 extensions in exported header
Fix issues reported by check-includes.sh:

 rte_crypto_sym.h:586:3: error: anonymous structs are a C11 extension
     [-Werror,-Wc11-extensions]
 rte_crypto_sym.h:510:2: error: anonymous unions are a C11 extension
     [-Werror,-Wc11-extensions]

Fixes: b59502a5e3d0 ("cryptodev: add AEAD parameters in crypto operation")

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
Acked-by: Pablo de Lara <pablo.de.lara.guarch@intel.com>