examples/multi_process: fix build
Fix bug with undeclared variable name and
calling a variable that is not member of struct.

CC main.o
l2fwd_fork/main.c:  In function ‘main’: l2fwd_fork/main.c:1043:33:
 error: ‘dev_info’ undeclared (first use in this function)
 rte_eth_dev_info_get(portid, &dev_info);

l2fwd_fork/main.c:1043:33: note: each undeclared identifier is
reported only once for each function it appears in
l2fwd_fork/main.c:1077:11: error: ‘struct rte_eth_txconf’
has no member named ‘tx_offloads’
   txq_conf.tx_offloads = local_port_conf.txmode.offloads;

Fixes: f8c02ca878af ("examples/multi_process: convert to new ethdev offloads API")
Cc: stable@dpdk.org

Signed-off-by: Emma Kenny <emma.kenny@intel.com>
Acked-by: Ferruh Yigit <ferruh.yigit@intel.com>
Acked-by: Shahaf Shuler <shahafs@mellanox.com>