eventdev: fix missing includes
The PCI helper file depends on some EAL definitions.
Spotted with devtools/check-includes.sh:
	error: implicit declaration of function ‘rte_eal_process_type’
	error: ‘RTE_PROC_PRIMARY’ undeclared
	error: implicit declaration of function ‘rte_socket_id’

There was also this error because the inline keyword was missing:
	error: ‘rte_event_pmd_pci_probe’ defined but not used

Fixes: 9a8269d56942 ("eventdev: make PCI probe and remove functions optional")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>
Acked-by: John McNamara <john.mcnamara@intel.com>