net/ixgbe: fix build with gcc 4.5.1
On SUSE11 with gcc 4.5.1 the following build error occurred,
most likely because of improper handling of annonymous unions:

drivers/net/ixgbe/ixgbe_ipsec.c:579:4: error:
	unknown field ‘ipsec’ specified in initializer

Fixes: 9a0752f498d2 ("net/ixgbe: enable inline IPsec")

Signed-off-by: Radu Nicolau <radu.nicolau@intel.com>