ivshmem: fix for modified mempool struct
struct rte_mempool changed its "ring" field to "pool_data"

"ring" field is accessed by ivshmem library, and updated to "pool_data"

This patch fixes the compile error:

lib/librte_ivshmem/rte_ivshmem.c:
 In function 'add_mempool_to_metadata':
 lib/librte_ivshmem/rte_ivshmem.c:584:32:
 error: 'const struct rte_mempool' has no member named 'ring'
  return add_ring_to_metadata(mp->ring, config);
                                ^~

Fixes: 449c49b93a6b ("mempool: support handler operations")

Signed-off-by: Ferruh Yigit <ferruh.yigit@intel.com>
Acked-by: David Hunt <david.hunt@intel.com>